# Generated by Django 4.1.3 on 2022-11-19 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Titulo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tiempo", models.PositiveIntegerField()),
                ("precio", models.PositiveIntegerField()),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Titulo.tiendas"
                    ),
                ),
            ],
        ),
    ]
