# Generated by Django 4.1.3 on 2022-11-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Titulo", "0002_productos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("rol", models.PositiveIntegerField()),
                ("correo", models.CharField(max_length=200)),
                ("telefono", models.PositiveIntegerField()),
            ],
        ),
    ]
