# Generated by Django 4.1.3 on 2022-11-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Titulo", "0003_usuarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarios",
            name="n_fila",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
