# Generated by Django 4.1.3 on 2022-11-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Titulo", "0004_usuarios_n_fila"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuarios",
            name="rol",
        ),
        migrations.RemoveField(
            model_name="usuarios",
            name="telefono",
        ),
    ]
