# Generated by Django 4.1.3 on 2022-11-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Titulo", "0005_remove_usuarios_rol_remove_usuarios_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarios",
            name="estado_pedido",
            field=models.BooleanField(default=False),
        ),
    ]
